version: '3.4'

services:
  webapplication4:
    image: ${DOCKER_REGISTRY-}webapplication4
    build:
      context: .
      dockerfile: WebApplication4/Dockerfile
  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379" 